name = "WebTools"
uuid = "27fda2ff-bbf2-488c-ae6b-41176655c1cd"
authors = ["Paco Ho"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
